/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import javax.swing.JFrame;

/**
 *
 * @author Sebastián
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    JFrame login;

    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCompleteName = new javax.swing.JLabel();
        jLabelSex = new javax.swing.JLabel();
        jLabelSuperUser = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jComboBoxSuperUser = new javax.swing.JComboBox<>();
        jComboBoxSex = new javax.swing.JComboBox<>();
        jTextFieldCompleteName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCompleteName.setText("Complete Name");
        getContentPane().add(jLabelCompleteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabelSex.setText("Sex");
        getContentPane().add(jLabelSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabelSuperUser.setText("SuperUser");
        getContentPane().add(jLabelSuperUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jButtonRegister.setText("Regist");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        jComboBoxSuperUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        getContentPane().add(jComboBoxSuperUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jComboBoxSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N", "Y" }));
        getContentPane().add(jComboBoxSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));
        getContentPane().add(jTextFieldCompleteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 100, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed

    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonExitActionPerformed

    public void login(JFrame login) {
        this.login = login;
        this.login.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JComboBox<String> jComboBoxSex;
    private javax.swing.JComboBox<String> jComboBoxSuperUser;
    private javax.swing.JLabel jLabelCompleteName;
    private javax.swing.JLabel jLabelSex;
    private javax.swing.JLabel jLabelSuperUser;
    private javax.swing.JTextField jTextFieldCompleteName;
    // End of variables declaration//GEN-END:variables
}
