/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cadastro;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebastián
 */
public class Cadastro extends javax.swing.JFrame {

    private final UsuarioController uc = new UsuarioController();

    /**
     * Creates new form Cadastro
     */
    JFrame login;

    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCompleteName = new javax.swing.JLabel();
        jLabelSuperUser = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jComboBoxSuperUser = new javax.swing.JComboBox<>();
        jTextFieldCompleteName = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCompleteName.setText("Complete Name");
        getContentPane().add(jLabelCompleteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabelSuperUser.setText("SuperUser");
        getContentPane().add(jLabelSuperUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jButtonRegister.setText("Regist");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 30));

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, 30));

        jComboBoxSuperUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N", "Y" }));
        getContentPane().add(jComboBoxSuperUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));
        getContentPane().add(jTextFieldCompleteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 140, -1));

        jLabelUsername.setText("User Name");
        getContentPane().add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));
        getContentPane().add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 140, -1));

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, 30));

        jLabelPassword.setText("Password");
        getContentPane().add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));
        getContentPane().add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 140, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        String username = jTextFieldUsername.getText();
        String completeName, password;
        int selectedItem;

        Usuario user = uc.getUser(username);

        if (user == null) {
            completeName = jTextFieldCompleteName.getText();
            password = jPasswordFieldPassword.getText();
            selectedItem = jComboBoxSuperUser.getSelectedIndex();

            uc.addUser(new Usuario(completeName, username, password, (selectedItem != 0)));
        } else {
            int reply = JOptionPane.showConfirmDialog(null, "DO YOU ARE OVERWRITING AN EXISTED USER?",
                    "WARNING", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                if (reply == JOptionPane.YES_OPTION) {
                    jTextFieldUsername.setText(user.getUserName());

                    completeName = jTextFieldCompleteName.getText();
                    password = jPasswordFieldPassword.getText();
                    selectedItem = jComboBoxSuperUser.getSelectedIndex();

                    
                    uc.changeCompleteName(user.getUserName()
                            , user.getPassword(), completeName);
                    uc.changePassword(user.getUserName(), user.getPassword(), password);
                    user.setPassword(password);
                    uc.changeUsername(user.getUserName(), user.getPassword(), username);
                }

            }
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        String username = jTextFieldUsername.getText();

        Usuario user = uc.getUser(username);

        if (user != null) {
            jTextFieldUsername.setText(user.getUserName());
            jTextFieldCompleteName.setText(user.getCompleteName());
            jComboBoxSuperUser.setSelectedIndex(user.isIsSuperUser() ? 1 : 0);
        } else {
            JOptionPane.showMessageDialog(rootPane, "USERNAME INCORRECT", "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    public void login(JFrame login) {
        this.login = login;
        this.login.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<String> jComboBoxSuperUser;
    private javax.swing.JLabel jLabelCompleteName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSuperUser;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldCompleteName;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
